language: ruby

rvm:
  - 2.5
  - 2.6
  - 2.7

install: ./bin/setup

jobs:
  include:
    - stage: deploy
      rvm: 2.7
      install: ./bin/setup
      script:
        - echo Deploy
        - echo $TRAVIS_PULL_REQUEST
        - echo $TRAVIS_BRANCH
        - echo $TRAVIS_TAG
      deploy:
        provider: rubygems
        gemspec: rspock.gemspec
        gem: rspock
        on:
          all_branches: true
            condition: '"$TRAVIS_PULL_REQUEST" = "false" && ( "$TRAVIS_BRANCH" = "master" || "$TRAVIS_BRANCH" = "$TRAVIS_TAG" )'
        api_key:
          secure: rIfUyBSv8ETaJ06vDiVGnhjNG9aiwa+h5ud/8D7/ieJQzpbvZY7N+5R5buHcEIdWIpj/FrkO8H1QuTrB8VDpa+ckDzAXoQKf7EsXtZYGPEwLymfpVCIzix8/8Wbu2lmsLwexAFDZ3YWUZHga1hOc+FuiI2I0TiFsjnzU+mPxdKnpDH1H2ZAUecW0DcEb3zEVtTV4oSgGMYPG2493gjUFnVAEbq1ODPtLKJ2qQw2R0Es20h1QQ0w06LNCcQ9XfoJY/aWTQJHp9uolmhXh97/NTntNvPTXDhv6aCTldtI/A5PuRl03CRtsHd5qLNt23hSCNBGnkZx1uEirTVSfSrha/XOJ4OopMYYa4DkbzSLC/yfpyfdvqW+ewymbOf9EjVqkQVtKb9rul8Gw5QlVQNhu+zpL0zTsC4BLmna4PrtqjeUVkhsOtXpE+rMDFjrjbFS89+VwHLzGipJDA4N5eRv1NB5s4Lkj5CExOBG2MsKlxN0+KYe5Gm255lP+JI9TUgV+26BitStBpZLv1/brLR5Ui9Z5U+4mH6f/DRLgMl8cOkuv9VABn6NEcFW3gbmVs4TaykcQdiozOIat7Zi+H4PcZ2bZcMvY8qCZgcEJDepg9nF4ArnxYlrnYkKdEM7jleryNS6whVM67k6IfrQnDyesvI5gsH4YNAkMtVl1TYPDa7s=
